name: PR Title check

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: read
  contents: read

jobs:
  enforce-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PR Title is Conventional Commit
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            chore
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
